# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-05-02 15:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import screen.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentKind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Update Date')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('tag', models.CharField(max_length=100, verbose_name='Tag')),
            ],
            options={
                'ordering': ('name',),
                'verbose_name': 'Document Kind',
                'verbose_name_plural': 'Document Kinds',
            },
        ),
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Update Date')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('screen_key', models.CharField(max_length=30, unique=True, verbose_name='Screen Key')),
                ('screen_secret', models.CharField(max_length=50, unique=True, verbose_name='Screen Secret')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'ordering': ('name',),
                'verbose_name': 'Screen',
                'verbose_name_plural': 'Screens',
            },
        ),
        migrations.CreateModel(
            name='ScreenContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Update Date')),
                ('document', models.FileField(blank=True, null=True, upload_to=screen.models.set_screen_document_upload_path, verbose_name='Document')),
                ('text', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Text')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('kind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='screen.DocumentKind', verbose_name='Kind')),
                ('screens', models.ManyToManyField(blank=True, to='screen.Screen', verbose_name='Screens')),
            ],
            options={
                'ordering': ('-update_date',),
                'verbose_name': 'Screen Content',
                'verbose_name_plural': 'Screen Contents',
            },
        ),
    ]
